version: "3"
services:
   database:
       build: https://github.com/maxdoom-com/docker-compose-mysql10.5.git
       env_file: .env
       volumes:
           - ./mysql:/var/lib/mysql
           - ./etc/custom/mariadb.conf:/etc/my.cnf.d/custom-mariadb.conf
